name: NPM Audit Fix Run
on:
  workflow_dispatch:
    inputs:
      force:
        description: 'Use --force flag for npm audit fix?'
        required: true
        type: boolean
      base_branch:
        description: 'Specify a base branch'
        required: false
        default: 'main'
      script:
        description: 'Script to run after audit fix'
        required: false
        default: 'npm run package'

  schedule:
    - cron: '0 0 * * 1'

jobs:
  audit-fix:
    uses: step-security/reusable-workflows/.github/workflows/audit_fix.yml@v1
    with:
      force: ${{ inputs.force || false }}
      base_branch: ${{ inputs.base_branch || 'main' }}
      script: ${{ inputs.script || 'npm run package' }}

permissions:
  contents: write
  pull-requests: write
  packages: read
  issues: write
